server.port: 9091
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URL}

logging:
  level:
    org.springframework.security: trace
    com.example.resource.user: debug
