server:
  port: 9000

logging:
  level:
    org.springframework: debug

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    open-in-view: false
    show-sql: true


